# Generated by Django 4.0.3 on 2022-03-30 17:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CRM_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="CRM_core.student",
                    ),
                ),
                ("firstName", models.CharField(max_length=10)),
                ("lastName", models.CharField(max_length=25)),
                (
                    "companyName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nip", models.CharField(blank=True, max_length=10, null=True)),
                ("street", models.CharField(max_length=200)),
                ("postCode", models.CharField(max_length=6)),
                ("town", models.CharField(max_length=20)),
                ("country", models.CharField(default="Poland", max_length=20)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paymentDate", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="CRM_core.student",
                    ),
                ),
            ],
        ),
    ]
