# Generated by Django 4.0.3 on 2022-05-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.CharField(max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.language'),
        ),
    ]
